<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texto [
  <!ELEMENT texto (titulo,  parrafo, url?)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT parrafo (abreviatura+)>
  <!ELEMENT parrafo (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
]>              

<texto>
        <titulo>XML explicado a los ni침os</titulo>
    <parrafo>El 
        <abreviatura>XML</abreviatura>
        define c칩mo crear lenguajes de marcas.
        </parrafo>
        <parrafo>Las marcas se a침aden a un documento de texto para a침adir informacion</parrafo>
    <url>www.example.org</url>
</texto>